### PR TITLE
Sync csc_master with upstream/master

### PR DESCRIPTION
**Pull request by martbhell**
<pre>
git fetch upstream
git merge --ff-only upstream/master
git checkout -B CCCP-2844-2
git cherry-pick csc_master
git push origin CCCP-2844-2
</pre>

### CODE REVIEW

**Comment by junousi** [comment]
This looks fine, but since I'm only 99% sure, repeating the question from Flowdock:

Should this get the "Rebase and merge" green button treatment? Or even some extra stuff from CLI?

**Comment by martbhell** [comment]
Ah my bad. Rebase and merge sound right.

**Comment by junousi** [comment]
Now that is strange.

The "Rebase and merge" button spoke of 250 commits, but now it claims only 1 was merged? Is this now the desired state or not quite?

**Comment by martbhell** [comment]
Hmm. We could check in a few days when there are more commits upstream if we can fast-forward in changes.

**Comment by martbhell** [comment]
https://github.com/CSCfi/tempest/tree/csc_master said ~777 commits ahead and ~1444 commits behind. So something fishy. 

I did
<pre>
git branch -D csc_master
git checkout master
git checkout -B csc_master
git cherry-pick 2b50745
git push origin csc_master --force
</pre>

I guess syncing repos should not be done with PRs. Sorry for that.

**Comment by junousi** [comment]
> I guess syncing repos should not be done with PRs. Sorry for that.

I've done it once with 

```
git remote something
git pull (or maybe fetch) some_flags
git remote something
git push some_flags
```

And that seemed somehow clunky so honestly not sure what's the "best" way. Whatever works I guess :)

**Pull request merged**
